#!/bin/bash

#DEBHELPER#

# Add support for new MediaTek adapters
echo "mt7921u" > /etc/modules-load.d/mt7921u.conf

# Support Comfast CF-953AX USB adapter
echo 'SUBSYSTEM=="drivers", DEVPATH=="/bus/usb/drivers/mt7921u", ATTR{new_id}="3574 6211"' > /etc/udev/rules.d/99-cf95x.rules

# Support Netgear Nighthawk AXE3000 USB adapter
echo 'SUBSYSTEM=="drivers", DEVPATH=="/bus/usb/drivers/mt7921u", ATTR{new_id}="0846 9060"' > /etc/udev/rules.d/99-axe3000.rules

# Apply changes immediately without requiring a reboot
modprobe mt7921u
